CCSTD= -g -std=c++0x -DVIXIPCTEST
CFLAGS = -c -Wall $(CCSTD) 
CC = g++
EXEC = test
INCLUDE= -I./ -I$(BORA_ROOT)/lib/public -I${BORA_ROOT}/public -I${BORA_ROOT}/lib/distribute
LIBSPATH= -L${BORA_ROOT}/build/obj-x64/vddk/lib
LIBS = -l-fuseMountIPC-obj -lrt

#OBJECTS = testop $(EXEC) testmmap testst
OBJECTS = $(EXEC) 

all :  $(OBJECTS)

test : testMesgQue.cpp
	$(CC) $(CCSTD) -o $(EXEC)  $? $(INCLUDE) $(LIBSPATH) $(LIBS)

clean : 
	rm -rf $(OBJECTS) *.o *.gch  core.*
